# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: stage 

on:
  push:
    branches:
      - 0625/build-prep
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run cicd:lint --if-present
          npm run cicd:build --if-present
          npm run cicd:test --if-present
      - name: dist-server
        run: |
          mkdir dist-server
          mv ./dist/src/*.* dist-server
          cp package.json dist-server
          ls dist-server

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: |
               dist-server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'stage'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: '4tt-1'
          slot-name: 'stage'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_33963AE817BA4C4680886CF4A8DCAE14 }}
          package: .
      - name: Ping stage
        id: hello
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://4tt-1-stage.azurewebsites.net"
          expected-statuses: "200,301"
  swap: 
    runs-on: ubuntu-latest
    needs: deploy
    steps: 
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az webapp deployment slot swap --slot stage --target-slot production --action swap --name 4tt-1 --resource-group basic-express-typescript --verbose
    - name: Ping production
      id: hello
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://4tt-1.azurewebsites.net"
        expected-statuses: "200,301"