# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - 4tt-1

on:
  push:
    branches:
      - 4t/0620-swap
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run cicd:build --if-present
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: |
               dist
               !./node_modules

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'stage'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: '4tt-1'
          slot-name: 'stage'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_33963AE817BA4C4680886CF4A8DCAE14 }}
          package: .
  swap: 
    runs-on: ubuntu-latest
    needs: deploy
    steps: 
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/scripts/app-service-swap-slot.sh
          $GITHUB_WORKSPACE/scripts/app-service-swap-slot.sh
